"""One-shot seed: reads weed catalog data and inserts into weed_species.

Run once: python seed_weed_catalog.py
Safe to re-run: ON CONFLICT (slug) DO NOTHING prevents duplicates."""

import asyncio
import json
from database import init_pool, close_pool, get_db

WEEDS = [
    # ── GAZON (lawn weeds) ──────────────────────────────────────────────────
    {
        "slug": "paardenbloem",
        "common_name_nl": "Paardenbloem",
        "latin_name": "Taraxacum officinale",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Molsla", "Pisbloem"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Grote gele bloemhoofdjes op holle stengel",
            "leaf_shape": "Diep ingesneden, getand",
            "growth_form": "rozettend",
            "max_height_cm": 40,
            "distinguishing": "Holle stengel met wit melksap; alles uit een rozet",
            "look_alikes": ["paardenbloem"],
        },
        "habitat": {
            "places": ["gazon", "border", "moestuin"],
            "soil_types": ["klei", "zand", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [4, 5, 6],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad", "wortelfragmenten"],
            "removal_method": "Uitsteken met onkruidsteker of penwortel volledig uitgraven",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Verwijder voor de pluisvorming, anders zaait hij zich massaal uit",
            "prevention": "Gazon dicht en gezond houden; kale plekken doorzaaien",
        },
        "edible": True,
        "edible_note": "Jong blad in salades, bloemen voor siroop of wijn, wortel voor koffie-achtige drank",
        "interesting": "Een plant kan tot 5000 zaden produceren; pluizen leggen kilometers af",
        "native_to_nl": True,
    },
    {
        "slug": "madeliefje",
        "common_name_nl": "Madeliefje",
        "latin_name": "Bellis perennis",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Meizoentje", "Koeienbloem"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine bloemhoofdjes met wit lintbloemen en geel hart",
            "leaf_shape": "Spatelvormig, stomp",
            "growth_form": "rozettend",
            "max_height_cm": 15,
            "distinguishing": "Kleine witte bloempjes met geel hart; rozet plat tegen de grond",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "tegels", "border"],
            "soil_types": ["klei", "zand", "humus", "voedselrijk"],
            "active_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "bloom_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad", "uitlopers"],
            "removal_method": "Uitsteken met onkruidsteker of handmatig uittrekken",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "Makkelijk te verwijderen, maar komt snel terug in kaal gazon",
            "prevention": "Gazon niet te kort maaien; hoger gras verdringt madeliefjes",
        },
        "edible": True,
        "edible_note": "Bloemen en jong blad eetbaar in salades; bloemknoppen in azijn inmaken",
        "interesting": "Bloeit bijna het hele jaar door; bloempjes sluiten zich 's avonds en bij regen",
        "native_to_nl": True,
    },
    {
        "slug": "witte-klaver",
        "common_name_nl": "Witte klaver",
        "latin_name": "Trifolium repens",
        "family": "Vlinderbloemenfamilie (Fabaceae)",
        "common_names": ["Klaver"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Ronde bolletjes van kleine witte bloempjes",
            "leaf_shape": "Drietallig, rond tot ovaal met lichte V-vormige tekening",
            "growth_form": "kruipend",
            "max_height_cm": 20,
            "distinguishing": "Kruipende stengels die wortelen op knopen; karakteristiek drietallig blad",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "border", "tegels"],
            "soil_types": ["klei", "zand", "arm"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [5, 6, 7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad", "uitlopers"],
            "removal_method": "Uitsteken of handmatig uittrekken; zorg dat alle kruipstengels meegenomen worden",
            "removal_difficulty": "gemiddeld",
            "urgency": "laag",
            "removal_tip": "In perken one-shot verwijderen kan; in gazon juist nuttig als natuurlijke stikstofbinder",
            "prevention": "Gazon voldoende bemesten; klaver gedijt op stikstofarme bodem",
        },
        "edible": True,
        "edible_note": "Bloemen en jong blad in salades; bloemen zoetig van smaak",
        "interesting": "Bindt stikstof uit de lucht via wortelknolletjes; een teken van stikstofarme bodem",
        "native_to_nl": True,
    },
    {
        "slug": "smalle-weegbree",
        "common_name_nl": "Smalle weegbree",
        "latin_name": "Plantago lanceolata",
        "family": "Weegbreefamilie (Plantaginaceae)",
        "common_names": ["Hondsribben"],
        "appearance": {
            "flower_color": "bruin",
            "flower_shape": "Korte bruine aren op lange dunne stelen",
            "leaf_shape": "Lancetvormig, duidelijk generfd",
            "growth_form": "rozettend",
            "max_height_cm": 50,
            "distinguishing": "Lange smalle bladeren met diepe nerven; bruine bloemaren op kale stelen",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "border", "braakliggend"],
            "soil_types": ["klei", "zand", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10, 11],
            "bloom_months": [5, 6, 7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker; penwortel volledig verwijderen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Verwijderen voor bloei voorkomt zaadverspreiding",
            "prevention": "Gazon gezond houden; verdichte bodem beluchten want weegbree duidt op verdichting",
        },
        "edible": True,
        "edible_note": "Jong blad in salades; zaadknoppen rauw of kort gebakken",
        "interesting": "Traditioneel gebruikt tegen hoest; blad helpt bij insectenbeten (in de huid wrijven)",
        "native_to_nl": True,
    },
    {
        "slug": "grote-weegbree",
        "common_name_nl": "Grote weegbree",
        "latin_name": "Plantago major",
        "family": "Weegbreefamilie (Plantaginaceae)",
        "common_names": ["Wegblad"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Lange groene aren op stevige stelen",
            "leaf_shape": "Breed ovaal, parallel generfd",
            "growth_form": "rozettend",
            "max_height_cm": 30,
            "distinguishing": "Brede platte bladeren tegen de grond; groene bloemaren met witte meeldraden",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "gazon", "braakliggend"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [5, 6, 7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken of handmatig uittrekken; vezelige wortelkluit meenemen",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "Vooral tussen tegels makkelijk te verwijderen",
            "prevention": "Voegen tussen tegels vullen met voegzand",
        },
        "edible": True,
        "edible_note": "Jong blad in salades of gekookt als spinazie",
        "interesting": 'Groeit waar veel wordt gelopen - vandaar de naam "wegblad". Verdraagt betreding extreem goed',
        "native_to_nl": True,
    },
    {
        "slug": "kruipende-boterbloem",
        "common_name_nl": "Kruipende boterbloem",
        "latin_name": "Ranunculus repens",
        "family": "Ranonkelfamilie (Ranunculaceae)",
        "common_names": ["Boterbloem"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Glanzende goudgele bloemen met 5 kroonbladen",
            "leaf_shape": "Drietallig, donkergroen, vaak gevlekt",
            "growth_form": "kruipend",
            "max_height_cm": 40,
            "distinguishing": "Kruipende uitlopers die wortelen; glanzende botergele bloemen",
            "look_alikes": ["scherpe-boterbloem"],
        },
        "habitat": {
            "places": ["gazon", "vochtig", "border", "moestuin"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [5, 6, 7, 8],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad", "uitlopers"],
            "removal_method": "Uitsteken met onkruidsteker; alle uitlopers meenemen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Laat geen stukjes uitloper achter - elke knoop maakt een nieuwe plant",
            "prevention": "Bodem verbeteren (drainage); boterbloem gedijt op natte plekken",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Alle boterbloemsoorten zijn giftig voor vee; het sap kan huidirritatie veroorzaken",
        "native_to_nl": True,
    },
    {
        "slug": "paarse-dovenetel",
        "common_name_nl": "Paarse dovenetel",
        "latin_name": "Lamium purpureum",
        "family": "Lipbloemenfamilie (Lamiaceae)",
        "common_names": ["Dovenetel"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Kleine paarse lipbloempjes in kransen",
            "leaf_shape": "Hartvormig, gekarteld, paars aangelopen aan de top",
            "growth_form": "staand",
            "max_height_cm": 30,
            "distinguishing": "Paarse bovenste bladeren en kleine paarse lipbloemen; lijkt op brandnetel maar prikt niet",
            "look_alikes": ["brandnetel"],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend"],
            "soil_types": ["klei", "zand", "humus", "voedselrijk"],
            "active_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "bloom_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; ondiep wortelend dus makkelijk",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "Bloeit al in maart; vroege bijenvoedselbron - overweeg wat te laten staan",
            "prevention": "Bodem bedekt houden; mulch aanbrengen in borders",
        },
        "edible": True,
        "edible_note": "Jonge toppen en bloemen in salades of thee",
        "interesting": "Vroegste voorjaarsbloeier; een van de eerste voedselbronnen voor hommelkoninginnen",
        "native_to_nl": True,
    },
    {
        "slug": "straatgras",
        "common_name_nl": "Straatgras",
        "latin_name": "Poa annua",
        "family": "Grassenfamilie (Poaceae)",
        "common_names": ["Vogelgras"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Kleine groene pluimen op korte stengels",
            "leaf_shape": "Smal, zacht, met bootvormige bladtop",
            "growth_form": "polvormend",
            "max_height_cm": 20,
            "distinguishing": "Kleine graspolletjes die het hele jaar bloeien; bootvormige bladpunt",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "moestuin", "border", "gazon"],
            "soil_types": ["klei", "zand", "humus"],
            "active_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "bloom_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "sun_preference": "all",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken of schoffelen; ondiep wortelend",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "Bloeit het hele jaar door; verwijderen voor zaadvorming is lastig - blijf consequent",
            "prevention": "Voegen tussen tegels vullen; dikke mulchlaag in borders",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Een van de meest succesvolle planten ter wereld; groeit zelfs op Antarctica (geintroduceerd)",
        "native_to_nl": False,
    },
    {
        "slug": "muurleeuwenbek",
        "common_name_nl": "Muurleeuwenbek",
        "latin_name": "Cymbalaria muralis",
        "family": "Weegbreefamilie (Plantaginaceae)",
        "common_names": ["Muurbloem"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Kleine lila lipbloempjes met gele keelvlek",
            "leaf_shape": "Klein, rond tot niervormig, gelobd",
            "growth_form": "kruipend",
            "max_height_cm": 5,
            "distinguishing": "Kleine klimop-achtige blaadjes en lila bloempjes; groeit in muurvoegen",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "border"],
            "soil_types": ["zand", "arm"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [5, 6, 7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; ondiep wortelend in voegen",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "Makkelijk te verwijderen; in oude muren juist charmant - overweeg te laten staan",
            "prevention": "Voegen in muren en terrassen dicht houden",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Na de bloei buigt de bloemsteel naar de muur toe om zaad in donkere spleten te deponeren",
        "native_to_nl": False,
    },
    {
        "slug": "varkensgras",
        "common_name_nl": "Gewoon varkensgras",
        "latin_name": "Polygonum aviculare",
        "family": "Duizendknoopfamilie (Polygonaceae)",
        "common_names": ["Varkensgras"],
        "appearance": {
            "flower_color": "roze",
            "flower_shape": "Kleine roze-witte bloempjes in bladoksels",
            "leaf_shape": "Klein, ovaal, blauwgroen",
            "growth_form": "kruipend",
            "max_height_cm": 10,
            "distinguishing": "Platliggende mat met kleine blauwgroene blaadjes; groeit zelfs in voegspleten",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "braakliggend", "moestuin"],
            "soil_types": ["klei", "zand", "arm"],
            "active_months": [5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Schoffelen of handmatig uittrekken; penwortel is taai maar meestal ondiep",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Verwijderen voor zaadvorming; een plant produceert tot 5000 zaden",
            "prevention": "Voegen dicht houden; bodembedekkers planten op kale plekken",
        },
        "edible": True,
        "edible_note": "Jong blad en zaden eetbaar; zaden bevatten veel zetmeel",
        "interesting": "Extreem tredbestendig; groeit op de meest belopen paden. Een van de oudste medicinale planten",
        "native_to_nl": True,
    },
    {
        "slug": "draadereprijs",
        "common_name_nl": "Draadereprijs",
        "latin_name": "Veronica filiformis",
        "family": "Weegbreefamilie (Plantaginaceae)",
        "common_names": ["Ereprijs"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Kleine lichtblauwe bloempjes met donkere adertjes",
            "leaf_shape": "Klein, rond tot ovaal",
            "growth_form": "kruipend",
            "max_height_cm": 5,
            "distinguishing": "Fijne draderige stengels die een dicht matje vormen; lichtblauwe bloempjes",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "border", "tegels"],
            "soil_types": ["klei", "zand", "humus"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [5, 6, 7],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["uitlopers", "wortelfragmenten"],
            "removal_method": "Handmatig uittrekken; alle draadstengels meenemen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Elk achtergebleven stengelfragment wortelt opnieuw - zorgvuldig verwijderen",
            "prevention": "Gazon niet te kort maaien; gezond gras verdringt ereprijs",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Oorspronkelijk uit de Kaukasus; in Nederland pas sinds de 19e eeuw. Verspreidt zich via grasmaaiers",
        "native_to_nl": False,
    },
    {
        "slug": "vogelmuur",
        "common_name_nl": "Vogelmuur",
        "latin_name": "Stellaria media",
        "family": "Anjerfamilie (Caryophyllaceae)",
        "common_names": ["Muur"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine stervormige witte bloempjes met diep ingesneden kroonbladen",
            "leaf_shape": "Klein, ovaal, frisgroen",
            "growth_form": "kruipend",
            "max_height_cm": 20,
            "distinguishing": "Een rij haartjes op de stengel (niet rondom); kleine witte sterbloempjes",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend", "tegels"],
            "soil_types": ["klei", "zand", "humus", "voedselrijk"],
            "active_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "bloom_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad"],
            "removal_method": "Schoffelen of handmatig uittrekken; heel makkelijk te verwijderen",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Een plant produceert 15.000 zaden en zaait het hele jaar door; blijf consequent verwijderen",
            "prevention": "Mulchen in borders; bodem in moestuin bedekt houden in winter",
        },
        "edible": True,
        "edible_note": "Heerlijk in salades; zacht en mild van smaak; ook gekookt als spinazie",
        "interesting": "Zaad blijft tientallen jaren kiemkrachtig in de bodem. Vogels zijn dol op de zaden - vandaar de naam",
        "native_to_nl": True,
    },

    # ── BORDER & MOESTUIN (border + vegetable garden weeds) ──────────────────
    {
        "slug": "zevenblad",
        "common_name_nl": "Zevenblad",
        "latin_name": "Aegopodium podagraria",
        "family": "Schermbloemenfamilie (Apiaceae)",
        "common_names": ["Hanenpoot", "Tuinmansverdriet"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Witte schermen van kleine bloempjes",
            "leaf_shape": "Drietallig of zeventallig samengesteld, eirond, getand",
            "growth_form": "staand",
            "max_height_cm": 80,
            "distinguishing": "Bladeren in groepjes van 7 (of 3); witte schermbloemen; verspreidt zich als een tapijt",
            "look_alikes": ["fluitenkruid"],
        },
        "habitat": {
            "places": ["border", "moestuin", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "wortelfragmenten"],
            "removal_method": "Uitgraven en alle wortelstokken verwijderen; niet schoffelen (verspreidt fragmenten)",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Elk achtergebleven stukje wortelstok loopt opnieuw uit; herhaal verwijderen meerdere seizoenen",
            "prevention": "Worteldoek of dikke mulch als barriere; borders met dichte beplanting vullen",
        },
        "edible": True,
        "edible_note": "Jong blad in salades of gekookt als spinazie; smaakt naar selderij-peterselie",
        "interesting": "In de Middeleeuwen gekweekt als groente; de naam verwijst naar gebruik tegen jicht (podagra)",
        "native_to_nl": True,
    },
    {
        "slug": "grote-brandnetel",
        "common_name_nl": "Grote brandnetel",
        "latin_name": "Urtica dioica",
        "family": "Brandnetelfamilie (Urticaceae)",
        "common_names": ["Brandnetel", "Netel"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Hangende groene trossen kleine bloempjes",
            "leaf_shape": "Langwerpig hartvormig, scherp getand, tegenoverstaand",
            "growth_form": "staand",
            "max_height_cm": 150,
            "distinguishing": "Brandharen op stengels en bladeren; groeit in grote groepen",
            "look_alikes": ["paarse-dovenetel"],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["zaad", "wortelstokken"],
            "removal_method": "Uitgraven met wortelstok; handschoenen met lange mouwen dragen",
            "removal_difficulty": "gemiddeld",
            "urgency": "hoog",
            "removal_tip": "Verwijderen voor zaadvorming in juli; uitgegraven planten NIET op de composthoop gooien",
            "prevention": "Wortelstokken volledig verwijderen; kale plekken direct beplanten",
        },
        "edible": True,
        "edible_note": "Jonge toppen koken voor soep, thee of stamppot; koken neutraliseert brandharen",
        "interesting": "Waardplant voor zeker 50 vlindersoorten; brandnetelgier is een uitstekende biologische meststof",
        "native_to_nl": True,
    },
    {
        "slug": "heermoes",
        "common_name_nl": "Heermoes",
        "latin_name": "Equisetum arvense",
        "family": "Paardenstaartfamilie (Equisetaceae)",
        "common_names": ["Paardenstaart", "Aker", "Kattenstaart"],
        "appearance": {
            "flower_color": "bruin",
            "flower_shape": "Bruine sporenaar op aparte bleke stengel in het voorjaar",
            "leaf_shape": "Geen echte bladeren; groene zijtakjes in kransen (lijken op bladeren)",
            "growth_form": "staand",
            "max_height_cm": 60,
            "distinguishing": "Groene kerstboom-achtige stengels; voelt ruw aan door kiezelzuur",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend", "vochtig"],
            "soil_types": ["klei", "zand", "arm"],
            "active_months": [4, 5, 6, 7, 8, 9],
            "bloom_months": [3, 4],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken"],
            "removal_method": "Herhaaldelijk uittrekken of schoffelen om wortelstokken uit te putten",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Wortelstokken kunnen tot 2 meter diep zitten; consequent bovengronds verwijderen put ze uiteindelijk uit",
            "prevention": "Bodem verbeteren met compost en kalk; heermoes wijst op arme, verdichte grond",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Bestaat al 300 miljoen jaar; bevat zoveel kiezelzuur dat het vroeger als schuurmiddel werd gebruikt",
        "native_to_nl": True,
    },
    {
        "slug": "kleefkruid",
        "common_name_nl": "Kleefkruid",
        "latin_name": "Galium aparine",
        "family": "Sterbladigenfamilie (Rubiaceae)",
        "common_names": ["Kleefkruid"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine witte bloempjes met 4 kroonblaadjes",
            "leaf_shape": "Smal, in kransen van 6-8 rond de stengel",
            "growth_form": "klimmend",
            "max_height_cm": 120,
            "distinguishing": "Bladeren en stengels bedekt met haakvormige haartjes die aan alles blijven kleven",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["border", "moestuin", "braakliggend", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9],
            "bloom_months": [5, 6, 7, 8],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; door de haakjes makkelijk in een beweging te verwijderen",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Verwijderen voor zaadvorming in juli; zaadjes blijven maandenlang kiemkrachtig en verspreiden zich via dieren",
            "prevention": "Borders dicht beplanten; in moestuin regelmatig schoffelen",
        },
        "edible": True,
        "edible_note": "Jonge toppen in soep of thee; zaden kunnen geroosterd worden als koffievervanger",
        "interesting": "De haakjes op de vruchtjes waren de inspiratie voor klittenband (Velcro)",
        "native_to_nl": True,
    },
    {
        "slug": "herderstasje",
        "common_name_nl": "Herderstasje",
        "latin_name": "Capsella bursa-pastoris",
        "family": "Kruisbloemenfamilie (Brassicaceae)",
        "common_names": ["Lepelblad", "Beursje"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine witte bloempjes in trosjes bovenaan de stengel",
            "leaf_shape": "Rozet onderaan: veervormig gelobd; stengelbladen: pijlvormig, stengelomvattend",
            "growth_form": "rozettend",
            "max_height_cm": 40,
            "distinguishing": 'Hartvormige driehoekige zaadbuisjes (de "tasjes"); rozet los van stengel',
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "tegels", "braakliggend", "border"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "bloom_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken of handmatig uittrekken; penwortel is dun en breekt makkelijk",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Bloeit en zaait het hele jaar door; blijf consequent verwijderen",
            "prevention": "Bodem in moestuin bedekt houden; mulchen in winter",
        },
        "edible": True,
        "edible_note": "Jong blad in salades of gekookt; zaadbuisjes rauw als pittige snack; smaakt naar mosterd",
        "interesting": "Zaadbuisjes lijken op de tas die herders vroeger droegen (bursa pastoris = herderstas)",
        "native_to_nl": True,
    },
    {
        "slug": "klein-hoefblad",
        "common_name_nl": "Klein hoefblad",
        "latin_name": "Tussilago farfara",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Hoefblad"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Geel bloemhoofdje op schubbige steel; lijkt op kleine paardenbloem",
            "leaf_shape": "Groot, rond tot hartvormig, hoefvormig; verschijnt NA de bloei",
            "growth_form": "staand",
            "max_height_cm": 25,
            "distinguishing": "Bloeit op kale stengels ver voor de bladeren verschijnen; bladeren lijken op paardenhoef",
            "look_alikes": ["paardenbloem"],
        },
        "habitat": {
            "places": ["braakliggend", "border", "tegels", "vochtig"],
            "soil_types": ["klei", "arm"],
            "active_months": [3, 4, 5, 6, 7, 8, 9],
            "bloom_months": [3, 4],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "zaad"],
            "removal_method": "Uitgraven met alle wortelstokken; herhaaldelijk uittrekken om uit te putten",
            "removal_difficulty": "moeilijk",
            "urgency": "gemiddeld",
            "removal_tip": "Wortelstokken kunnen meters ver uitlopen; graaf de hele kolonie uit",
            "prevention": "Bodembedekking en concurrentie van andere planten; kale grond vermijden",
        },
        "edible": True,
        "edible_note": "Jonge bloemen en bladeren voor thee (hoestthee); in kleine hoeveelheden gebruiken",
        "interesting": 'Al sinds de Oudheid gebruikt als hoestmiddel; de Latijnse naam tussilago betekent "hoestverdrijver"',
        "native_to_nl": True,
    },
    {
        "slug": "melganzenvoet",
        "common_name_nl": "Melganzenvoet",
        "latin_name": "Chenopodium album",
        "family": "Amarantenfamilie (Amaranthaceae)",
        "common_names": ["Wilde spinazie"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Groene bloempjes in dichte pluimen; weinig opvallend",
            "leaf_shape": "Ruitvormig tot lancetvormig, meelachtig wit bestoven",
            "growth_form": "staand",
            "max_height_cm": 150,
            "distinguishing": "Meelachtige witte bestuiving op bladeren (vooral jong); rechtopgaande groei tot manshoog",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "braakliggend", "border"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [5, 6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uittrekken of schoffelen voor zaadvorming; jonge planten makkelijk te verwijderen",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Een plant produceert tot 100.000 zaden; verwijder zodra je ze ziet",
            "prevention": "Moestuin niet kaal laten liggen in winter; groenbemester zaaien",
        },
        "edible": True,
        "edible_note": "Jong blad en toppen koken als spinazie; zaden eetbaar (vergelijkbaar met quinoa)",
        "interesting": "Nauwe verwant van quinoa; werd in Nederland tot de 19e eeuw als groente verbouwd",
        "native_to_nl": True,
    },
    {
        "slug": "perzikkruid",
        "common_name_nl": "Perzikkruid",
        "latin_name": "Persicaria maculosa",
        "family": "Duizendknoopfamilie (Polygonaceae)",
        "common_names": ["Wilgenblad", "Roodbil"],
        "appearance": {
            "flower_color": "roze",
            "flower_shape": "Dichte roze bloemaren",
            "leaf_shape": "Lancetvormig, vaak met donkere vlek in het midden",
            "growth_form": "staand",
            "max_height_cm": 80,
            "distinguishing": "Donkere vlek op de bladeren; roze bloemaren; rode stengelknopen",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [5, 6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken of schoffelen; ondiep wortelend",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "Zaden blijven lang kiemkrachtig; consequent verwijderen gedurende het seizoen",
            "prevention": "Mulchlaag aanbrengen; concurrentie van dichte beplanting",
        },
        "edible": False,
        "edible_note": None,
        "interesting": 'De donkere bladvlek is een natuurlijk merkteken - vandaar de alternatieve naam "roodbil"',
        "native_to_nl": True,
    },
    {
        "slug": "gekroesde-melkdistel",
        "common_name_nl": "Gekroesde melkdistel",
        "latin_name": "Sonchus asper",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Melkdistel"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Gele bloemhoofdjes in losse tuilen",
            "leaf_shape": "Stijf, donkergroen, stekelig getand, stengelomvattend met afgeronde oortjes",
            "growth_form": "staand",
            "max_height_cm": 90,
            "distinguishing": "Stekelige bladranden (gekroesd); wit melksap bij breken; bladeren omvatten de stengel",
            "look_alikes": ["gewone-melkdistel"],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker; penwortel volledig verwijderen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Verwijderen voor bloei; de pluizige zaden verspreiden zich snel",
            "prevention": "Regelmatig schoffelen in moestuin; mulch in borders",
        },
        "edible": True,
        "edible_note": "Jong blad in salades of gekookt; smaakt iets bitter",
        "interesting": "Het melksap werd traditioneel gebruikt tegen wratten; konijnen en cavia's zijn dol op het blad",
        "native_to_nl": True,
    },
    {
        "slug": "tuinwolfsmelk",
        "common_name_nl": "Tuinwolfsmelk",
        "latin_name": "Euphorbia peplus",
        "family": "Wolfsmelkfamilie (Euphorbiaceae)",
        "common_names": ["Wolfsmelk"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Kleine groene schijnbloemen (cyathia) met halvemaanvormige klieren",
            "leaf_shape": "Klein, ovaal, gaafrandig, zachtgroen",
            "growth_form": "staand",
            "max_height_cm": 30,
            "distinguishing": "Wit melksap bij breken; kleine groene bloempjes met opvallende gele klieren",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "tegels", "border"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; ondiep wortelend; handschoenen dragen tegen melksap",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "Zaait snel uit maar is klein en makkelijk te verwijderen; melksap kan huid irriteren",
            "prevention": "Mulchen; regelmatig wieden voordat zaad rijpt",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Het melksap wordt in de volksgeneeskunde gebruikt tegen huidkanker; bevat diterpeenesters die huid irriteren",
        "native_to_nl": True,
    },
    {
        "slug": "hondsdraf",
        "common_name_nl": "Hondsdraf",
        "latin_name": "Glechoma hederacea",
        "family": "Lipbloemenfamilie (Lamiaceae)",
        "common_names": ["Aardveil"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Paarsblauwe lipbloempjes met donkere vlekjes op de onderlip",
            "leaf_shape": "Rond tot niervormig, gekarteld, tegenoverstaand",
            "growth_form": "kruipend",
            "max_height_cm": 15,
            "distinguishing": "Kruipt over de grond en vormt dichte tapijten; blauwpaarse lipbloempjes; blad ruikt aromatisch bij kneuzen",
            "look_alikes": ["paarse-dovenetel"],
        },
        "habitat": {
            "places": ["gazon", "border", "vochtig", "tegels"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [4, 5, 6],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "oppervlakkig",
            "reproduces_via": ["uitlopers", "zaad"],
            "removal_method": "Handmatig uittrekken of harken; kruipstengels volgen en volledig verwijderen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Vormt dichte matten die ander laagblijvend spul verstikken; grondig verwijderen",
            "prevention": "Gazon niet te kort maaien; hoger gras verdringt hondsdraf",
        },
        "edible": True,
        "edible_note": "Jong blad in salades of soep; licht muntachtig van smaak; ook voor thee",
        "interesting": "Werd vroeger gebruikt om bier op smaak te brengen voor de introductie van hop",
        "native_to_nl": True,
    },

    # ── WOEKERAARS (invasive spreaders) ──────────────────────────────────────
    {
        "slug": "haagwinde",
        "common_name_nl": "Haagwinde",
        "latin_name": "Convolvulus sepium",
        "family": "Windefamilie (Convolvulaceae)",
        "common_names": ["Pispotjes", "Windeklimmer"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Grote witte trechtervormige bloemen (5-7 cm)",
            "leaf_shape": "Pijlvormig, groot, heldergroen",
            "growth_form": "klimmend",
            "max_height_cm": 300,
            "distinguishing": "Grote zuiver witte trechterbloemen; rechtswindend; enorme ondergrondse wortelstokken",
            "look_alikes": ["akkerwinde"],
        },
        "habitat": {
            "places": ["border", "moestuin", "braakliggend", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [5, 6, 7, 8, 9],
            "bloom_months": [7, 8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "zaad"],
            "removal_method": "Bovengronds herhaaldelijk uittrekken om wortelstokken uit te putten; niet schoffelen",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Wortelstokken kunnen meters ver lopen en brokstukken van 2 cm lopen opnieuw uit; uitputten duurt jaren",
            "prevention": "Planten in een korf plaatsen; niet in de compost gooien",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Een van de hardnekkigste invasieve soorten in tuinen; kan planten volledig overwoekeren en verstikken",
        "native_to_nl": True,
    },
    {
        "slug": "akkerwinde",
        "common_name_nl": "Akkerwinde",
        "latin_name": "Convolvulus arvensis",
        "family": "Windefamilie (Convolvulaceae)",
        "common_names": ["Kleine winde", "Akkerklokje"],
        "appearance": {
            "flower_color": "roze",
            "flower_shape": "Roze-witte trechtervormige bloemen (2-3 cm)",
            "leaf_shape": "Pijlvormig, klein, dofgroen",
            "growth_form": "klimmend",
            "max_height_cm": 150,
            "distinguishing": "Kleinere bloemen dan haagwinde; roze gestreept; bloemen geuren naar amandel",
            "look_alikes": ["haagwinde"],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend", "tegels"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [5, 6, 7, 8, 9],
            "bloom_months": [6, 7, 8],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "zaad"],
            "removal_method": "Herhaaldelijk uittrekken; elke 2 weken bovengronds verwijderen om uit te putten",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Wortelstokken tot 5 meter diep; alleen consequent bovengronds verwijderen werkt",
            "prevention": "Geen kale grond; dichte beplanting; zaadproductie voorkomen",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Ondergrondse wortelstokken kunnen 5 meter diep reiken; een van de moeilijkst te bestrijden onkruiden",
        "native_to_nl": True,
    },
    {
        "slug": "akkerdistel",
        "common_name_nl": "Akkerdistel",
        "latin_name": "Cirsium arvense",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Distel", "Boerenplaag"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Lila-paarse bloemhoofdjes in vertakte tuilen",
            "leaf_shape": "Langwerpig, stekelig getand, golvend",
            "growth_form": "staand",
            "max_height_cm": 120,
            "distinguishing": "Stekelige bladranden; lila-paarse bloemen; enorme ondergrondse uitlopers",
            "look_alikes": ["speerdistel"],
        },
        "habitat": {
            "places": ["moestuin", "border", "braakliggend"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "wortelfragmenten", "zaad"],
            "removal_method": "Herhaaldelijk afsteken onder de grond; niet schoffelen (verspreidt fragmenten)",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Elk wortelfragment van 1 cm kan een nieuwe plant vormen; een plant kan 40.000 zaden produceren",
            "prevention": "Afdekken met zwart plastic voor een heel groeiseizoen; anders jarenlang consequent verwijderen",
        },
        "edible": True,
        "edible_note": "Jonge stengels schillen en rauw eten; bloemen voor siroop; wortels gekookt",
        "interesting": "Mannelijke en vrouwelijke bloemen groeien op aparte planten; zaadpluis kan kilometers ver dragen",
        "native_to_nl": True,
    },
    {
        "slug": "ridderzuring",
        "common_name_nl": "Ridderzuring",
        "latin_name": "Rumex obtusifolius",
        "family": "Duizendknoopfamilie (Polygonaceae)",
        "common_names": ["Zurkel", "Paardenzuring"],
        "appearance": {
            "flower_color": "groen",
            "flower_shape": "Groene bloempjes in hoge, dichte pluimen; later roodbruin",
            "leaf_shape": "Zeer groot, ovaal tot langwerpig, met hartvormige voet",
            "growth_form": "staand",
            "max_height_cm": 120,
            "distinguishing": "Enorme bladeren (tot 40 cm); hoge roodbruine zaadpluimen; dikke vlezige penwortel",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "border", "vochtig", "braakliggend"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad", "wortelfragmenten"],
            "removal_method": "Uitgraven met hele penwortel; diep steken want penwortel kan 1 meter+ reiken",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Verwijderen voor zaadvorming; een plant produceert 60.000 zaden die 50 jaar kiemkrachtig blijven",
            "prevention": "Bekalken; zuring wijst op zure grond; dichte grasmat en niet te vaak maaien",
        },
        "edible": True,
        "edible_note": "Jong blad in kleine hoeveelheden in salades of gekookt; bevat oxaalzuur",
        "interesting": "Het blad bevat looizuur dat helpt tegen brandnetelprikken - groeit vaak in de buurt van brandnetels",
        "native_to_nl": True,
    },
    {
        "slug": "duizenknoop",
        "common_name_nl": "Japanse duizendknoop",
        "latin_name": "Fallopia japonica",
        "family": "Duizendknoopfamilie (Polygonaceae)",
        "common_names": ["Bamboe (onjuist)"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Witte bloempjes in pluimen in de bladoksels",
            "leaf_shape": "Groot, breed ovaal, toegespitst, gaafrandig",
            "growth_form": "staand",
            "max_height_cm": 300,
            "distinguishing": "Bamboe-achtige holle stengels; zigzag groeiwijze; enorme polvorming",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["border", "braakliggend", "vochtig"],
            "soil_types": ["klei", "zand", "humus"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [8, 9],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "wortelfragmenten"],
            "removal_method": "Uitgraven; NIET in compost; professionele bestrijding aanbevolen",
            "removal_difficulty": "moeilijk",
            "urgency": "hoog",
            "removal_tip": "Een fragment van 0.7 gram kan een nieuwe plant vormen; meld grote haarden bij de gemeente",
            "prevention": "Professioneel laten verwijderen; worteldoek alleen is onvoldoende",
        },
        "edible": True,
        "edible_note": "Jonge scheuten (tot 20 cm) rauw of gekookt; smaakt naar rabarber met citroen",
        "interesting": "Staat in de top 100 van meest invasieve soorten wereldwijd; breekt door asfalt en funderingen heen",
        "native_to_nl": False,
    },
    {
        "slug": "speerdistel",
        "common_name_nl": "Speerdistel",
        "latin_name": "Cirsium vulgare",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Wegdistel"],
        "appearance": {
            "flower_color": "paars",
            "flower_shape": "Grote paarse bloemhoofdjes met stekelige omwindselblaadjes",
            "leaf_shape": "Langwerpig, diep ingesneden, zeer stekelig",
            "growth_form": "staand",
            "max_height_cm": 150,
            "distinguishing": "Zeer stekelig van top tot teen; grote paarse bloemen; tweejarig (eerst rozet, dan bloeistengel)",
            "look_alikes": ["akkerdistel"],
        },
        "habitat": {
            "places": ["braakliggend", "border", "moestuin"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker in rozetstadium; handschoenen vereist",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Verwijderen in het eerste jaar (rozetstadium) is veel makkelijker dan in het tweede jaar",
            "prevention": "In rozetstadium verwijderen voor de bloeistengel zich ontwikkelt",
        },
        "edible": True,
        "edible_note": "Jonge bladeren (stekels verwijderen!) gekookt; bloembodem eetbaar als artisjok-achtig",
        "interesting": "Distelvinken zijn gespecialiseerd in het eten van distelzaden; de zaadpluizen worden gebruikt als nestmateriaal",
        "native_to_nl": True,
    },
    {
        "slug": "gewone-melkdistel",
        "common_name_nl": "Gewone melkdistel",
        "latin_name": "Sonchus oleraceus",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Hazenmelk"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Lichtgele bloemhoofdjes in losse tuilen",
            "leaf_shape": "Diep ingesneden, zacht, blauwgroen, met stengelomvattende spitse oortjes",
            "growth_form": "staand",
            "max_height_cm": 100,
            "distinguishing": "Zachte, niet-stekelige bladeren met wit melksap; bladeren omvatten de stengel met spitse slippen",
            "look_alikes": ["gekroesde-melkdistel"],
        },
        "habitat": {
            "places": ["moestuin", "braakliggend", "border"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken of schoffelen voor bloei; jonge planten makkelijk te verwijderen",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "Zaait massaal uit als je hem laat bloeien; een plant produceert duizenden pluiszaden",
            "prevention": "Regelmatig schoffelen; mulch aanbrengen in moestuin",
        },
        "edible": True,
        "edible_note": "Jong blad in salades (licht bitter); gekookt als spinazie; konijnenvoer bij uitstek",
        "interesting": "Een van de meest algemene akkeronkruiden ter wereld; zaden blijven jaren kiemkrachtig",
        "native_to_nl": True,
    },

    # ── OVERIGE (remaining common weeds) ─────────────────────────────────────
    {
        "slug": "bijvoet",
        "common_name_nl": "Bijvoet",
        "latin_name": "Artemisia vulgaris",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Wilde alsem"],
        "appearance": {
            "flower_color": "bruin",
            "flower_shape": "Kleine roodbruine bloemhoofdjes in dichte pluimen",
            "leaf_shape": "Diep ingesneden, veervormig; bovenzijde donkergroen, onderzijde witviltig",
            "growth_form": "staand",
            "max_height_cm": 150,
            "distinguishing": "Witviltige onderzijde van bladeren; aromatische geur bij kneuzen; roodbruine stengels",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["braakliggend", "border", "tegels"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad", "wortelstokken"],
            "removal_method": "Uitsteken of uittrekken; wortelstokken verwijderen",
            "removal_difficulty": "gemiddeld",
            "urgency": "gemiddeld",
            "removal_tip": "Kan flinke pollen vormen; verwijder hele plant inclusief wortelstokken",
            "prevention": "Kale grond vermijden; concurrentie van hogere planten beperkt bijvoet",
        },
        "edible": True,
        "edible_note": "Jong blad als kruid bij vette gerechten (eendenborst, gans); smaakt bitter-aromatisch",
        "interesting": "Traditioneel gebruikt in moxibustie (Chinese geneeskunde); een van de bitterste inheemse kruiden",
        "native_to_nl": True,
    },
    {
        "slug": "duizendblad",
        "common_name_nl": "Gewoon duizendblad",
        "latin_name": "Achillea millefolium",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Duizendblad", "Wondkruid"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Platte witte schermen van kleine bloemhoofdjes",
            "leaf_shape": "Zeer fijn verdeeld, veervormig, varenachtig",
            "growth_form": "staand",
            "max_height_cm": 60,
            "distinguishing": "Fijn verdeelde varenachtige bladeren; platte witte bloemschermen; aromatisch",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["gazon", "border", "braakliggend", "tegels"],
            "soil_types": ["klei", "zand", "arm"],
            "active_months": [3, 4, 5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "wortelstokken",
            "reproduces_via": ["wortelstokken", "zaad"],
            "removal_method": "Uitsteken met onkruidsteker; alle wortelstokken verwijderen",
            "removal_difficulty": "gemiddeld",
            "urgency": "laag",
            "removal_tip": "In gazon verdwijnt duizendblad door regelmatig maaien; in border is het een mooie inheemse plant",
            "prevention": "Gazon regelmatig maaien en bemesten; concurrentie in borders",
        },
        "edible": True,
        "edible_note": "Jong blad en bloemen in salades of thee; bitter-aromatisch",
        "interesting": "Al sinds de prehistorie gebruikt als wondkruid; Achilles gebruikte het volgens de mythe om wonden te helen",
        "native_to_nl": True,
    },
    {
        "slug": "canadese-fijnstraal",
        "common_name_nl": "Canadese fijnstraal",
        "latin_name": "Conyza canadensis",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["Canadese fijnstraal"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine wit-gele bloemhoofdjes in lange pluimen",
            "leaf_shape": "Smal, lancetvormig, behaard",
            "growth_form": "staand",
            "max_height_cm": 120,
            "distinguishing": "Lange rechte stengel met vele kleine bloempjes; pluizige zaadhoofdjes; groeit overal in de stad",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "braakliggend", "border", "moestuin"],
            "soil_types": ["zand", "arm"],
            "active_months": [5, 6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9, 10],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; heel makkelijk verwijderbaar",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Een plant produceert tot 250.000 pluiszaden; verwijderen zodra je ze ziet",
            "prevention": "Voegen tussen tegels dicht houden; kale grond vermijden",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Oorspronkelijk uit Noord-Amerika; een van de meest voorkomende stedelijke pioniersplanten in Nederland",
        "native_to_nl": False,
    },
    {
        "slug": "look-zonder-look",
        "common_name_nl": "Look-zonder-look",
        "latin_name": "Alliaria petiolata",
        "family": "Kruisbloemenfamilie (Brassicaceae)",
        "common_names": ["Knoflookkruid"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine witte bloempjes in eindstandige trossen",
            "leaf_shape": "Hartvormig tot rond, gekarteld, heldergroen; blad ruikt naar knoflook bij kneuzen",
            "growth_form": "staand",
            "max_height_cm": 100,
            "distinguishing": "Bladeren ruiken sterk naar knoflook bij kneuzen; witte bloemen met 4 kroonblaadjes",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["border", "vochtig", "braakliggend"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7],
            "bloom_months": [4, 5, 6],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uittrekken voor zaadvorming; tweejarig dus verwijder voor het tweede jaar",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "In het eerste jaar zit de plant als rozet dicht bij de grond; dan makkelijk te verwijderen",
            "prevention": "Verwijderen voor de zaden rijpen; zaden blijven meerdere jaren kiemkrachtig",
        },
        "edible": True,
        "edible_note": "Bladeren als knoflookvervanger in salades, pesto of soep; zaden pittig als mosterdzaad",
        "interesting": "Waardplant voor het oranjetipje, een van de mooiste voorjaarsvlinders; de rupsen eten de zaaddozen",
        "native_to_nl": True,
    },
    {
        "slug": "fluitenkruid",
        "common_name_nl": "Fluitenkruid",
        "latin_name": "Anthriscus sylvestris",
        "family": "Schermbloemenfamilie (Apiaceae)",
        "common_names": ["Fluitekruid"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Grote witte schermen van kleine bloempjes",
            "leaf_shape": "Drie- tot viervoudig geveerd, fijn, varenachtig",
            "growth_form": "staand",
            "max_height_cm": 120,
            "distinguishing": "Holle stengel (waar je op kunt fluiten); witte schermbloemen; bloeit massaal in bermen",
            "look_alikes": ["zevenblad"],
        },
        "habitat": {
            "places": ["border", "braakliggend", "vochtig", "moestuin"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [3, 4, 5, 6, 7],
            "bloom_months": [4, 5, 6],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker; penwortel volledig verwijderen",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Verwijderen voor zaadvorming in juni; zaait zichzelf massaal uit",
            "prevention": "Niet laten uitzaaien; een plant kan honderden nakomelingen produceren",
        },
        "edible": True,
        "edible_note": "Jong blad en stengels voor salades of soep; bloemschermen voor decoratie; smaakt naar kervel",
        "interesting": "De holle stengels kunnen als fluitje worden gebruikt - vandaar de naam; een van de vroegste schermbloemen in het voorjaar",
        "native_to_nl": True,
    },
    {
        "slug": "jacobskruiskruid",
        "common_name_nl": "Jacobskruiskruid",
        "latin_name": "Jacobaea vulgaris",
        "family": "Composietenfamilie (Asteraceae)",
        "common_names": ["St. Jacobskruid"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Heldere goudgele bloemhoofdjes in platte tuilen",
            "leaf_shape": "Diep ingesneden, donkergroen, met eindstandige grotere lob",
            "growth_form": "staand",
            "max_height_cm": 90,
            "distinguishing": "Felle goudgele bloemen in vlakke schermen; tweejarig; bladeren diep ingesneden",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["braakliggend", "gazon", "border", "tegels"],
            "soil_types": ["zand", "arm"],
            "active_months": [4, 5, 6, 7, 8, 9],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker; handschoenen dragen (giftig)",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Verwijderen voor zaadvorming; giftig voor paarden en vee - niet in hooi",
            "prevention": "Niet laten uitzaaien; op arme zandgrond kan het massaal opslaan",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Bevat pyrrolizidine-alkaloiden die leverschade veroorzaken bij paarden en vee; de zebrarups (St. Jacobsvlinder) is resistent en eet alleen deze plant",
        "native_to_nl": True,
    },
    {
        "slug": "gewone-raket",
        "common_name_nl": "Gewone raket",
        "latin_name": "Sisymbrium officinale",
        "family": "Kruisbloemenfamilie (Brassicaceae)",
        "common_names": ["Raketkruid"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Kleine lichtgele bloempjes in lange smalle trossen",
            "leaf_shape": "Diep ingesneden, met grote eindlob; onderste bladeren rozet",
            "growth_form": "staand",
            "max_height_cm": 60,
            "distinguishing": "Lange dunne zaaddozen die tegen de stengel aanliggen; rechtopgaande stijve groeiwijze",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["tegels", "braakliggend", "moestuin"],
            "soil_types": ["zand", "voedselrijk"],
            "active_months": [5, 6, 7, 8, 9, 10],
            "bloom_months": [6, 7, 8],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Uittrekken of schoffelen; penwortel breekt soms af maar plant sterft meestal",
            "removal_difficulty": "makkelijk",
            "urgency": "gemiddeld",
            "removal_tip": "Vooral in stedelijk gebied talrijk; makkelijk te verwijderen zolang ze niet hebben uitgezaaid",
            "prevention": "Voegen in bestrating dicht houden; regelmatig schoffelen",
        },
        "edible": True,
        "edible_note": "Jong blad en bloemen in salades; smaakt naar mosterd/raket; zaden als mosterdvervanger",
        "interesting": 'De plant werd vroeger door straatzangers gebruikt om hun stem te smeren - vandaar de Franse naam "herbe aux chantres"',
        "native_to_nl": True,
    },
    {
        "slug": "grote-klaproos",
        "common_name_nl": "Grote klaproos",
        "latin_name": "Papaver rhoeas",
        "family": "Papaverfamilie (Papaveraceae)",
        "common_names": ["Papaver", "Kolbleem"],
        "appearance": {
            "flower_color": "rood",
            "flower_shape": "Grote helderrode bloemen met zwarte vlek aan de basis van de kroonbladen",
            "leaf_shape": "Veerspletig, behaard",
            "growth_form": "staand",
            "max_height_cm": 70,
            "distinguishing": "Grote knalrode bloemen; zwarte vlek in het hart; behaarde stengels en knoppen",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["braakliggend", "border", "moestuin"],
            "soil_types": ["zand", "arm", "voedselrijk"],
            "active_months": [4, 5, 6, 7],
            "bloom_months": [6, 7],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "penwortel",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; penwortel is dun en breekt makkelijk",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "Eigenlijk geen echte onkruid; velen laten klaprozen bewust staan vanwege de schoonheid",
            "prevention": "Als je ze wilt weren: zaaddozen verwijderen voor ze opengaan; zaden blijven tientallen jaren kiemkrachtig",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Symbool van de Eerste Wereldoorlog; de zaden kunnen decennialang in de bodem sluimeren tot de grond verstoord wordt",
        "native_to_nl": True,
    },
    {
        "slug": "zwarte-nachtschade",
        "common_name_nl": "Zwarte nachtschade",
        "latin_name": "Solanum nigrum",
        "family": "Nachtschadefamilie (Solanaceae)",
        "common_names": ["Nachtschade"],
        "appearance": {
            "flower_color": "wit",
            "flower_shape": "Kleine witte stervormige bloempjes met gele meeldraden",
            "leaf_shape": "Ovaal tot ruitvormig, gaafrandig of ondiep getand",
            "growth_form": "staand",
            "max_height_cm": 60,
            "distinguishing": "Zwarte glanzende besjes na de bloei; witte sterbloempjes met opvallende gele helmhokjes",
            "look_alikes": [],
        },
        "habitat": {
            "places": ["moestuin", "braakliggend", "border"],
            "soil_types": ["klei", "zand", "voedselrijk"],
            "active_months": [6, 7, 8, 9, 10],
            "bloom_months": [7, 8, 9],
            "sun_preference": "zon",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Handmatig uittrekken; ondiep wortelend; handschoenen aan (plant is giftig)",
            "removal_difficulty": "makkelijk",
            "urgency": "hoog",
            "removal_tip": "Verwijder voor de bessen rijpen (groen naar zwart); bessen zijn giftig - zeker bij kinderen",
            "prevention": "Regelmatig wieden in moestuin; zaad blijft jaren kiemkrachtig",
        },
        "edible": False,
        "edible_note": None,
        "interesting": "Nauwe verwant van tomaat en aardappel; de onrijpe bessen bevatten solanine, een giftige alkaloide",
        "native_to_nl": True,
    },
    {
        "slug": "scherpe-boterbloem",
        "common_name_nl": "Scherpe boterbloem",
        "latin_name": "Ranunculus acris",
        "family": "Ranonkelfamilie (Ranunculaceae)",
        "common_names": ["Boterbloem"],
        "appearance": {
            "flower_color": "geel",
            "flower_shape": "Vijf glanzend gele kroonbladen, komvormig",
            "leaf_shape": "Handvormig diep ingesneden; stengelbladen smaller dan rozetbladen",
            "growth_form": "staand",
            "max_height_cm": 80,
            "distinguishing": "Geen uitlopers (in tegenstelling tot kruipende boterbloem); rechte stengels met bloemen op lange stelen",
            "look_alikes": ["kruipende-boterbloem"],
        },
        "habitat": {
            "places": ["gazon", "border", "vochtig"],
            "soil_types": ["klei", "humus", "voedselrijk"],
            "active_months": [4, 5, 6, 7, 8, 9],
            "bloom_months": [5, 6, 7],
            "sun_preference": "halfschaduw",
        },
        "removal": {
            "root_type": "vezelig",
            "reproduces_via": ["zaad"],
            "removal_method": "Uitsteken met onkruidsteker; vezelige wortelkluit meenemen",
            "removal_difficulty": "makkelijk",
            "urgency": "laag",
            "removal_tip": "In vochtige weilanden massaal aanwezig; in tuin eenvoudig te verwijderen",
            "prevention": "Bodem verbeteren (drainage); niet te veel beregenen",
        },
        "edible": False,
        "edible_note": None,
        "interesting": 'De botanische naam acris betekent "scherp" - verwijst naar de scherpe, brandende smaak van het sap',
        "native_to_nl": True,
    },
]


async def seed():
    async with get_db() as db:
        for w in WEEDS:
            await db.execute("""
                INSERT INTO weed_species
                    (slug, common_name_nl, latin_name, family, common_names,
                     appearance_json, habitat_json, removal_json,
                     edible, edible_note, interesting, native_to_nl)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (slug) DO NOTHING
            """, (
                w["slug"], w["common_name_nl"], w["latin_name"],
                w["family"], json.dumps(w.get("common_names", [])),
                json.dumps(w.get("appearance")),
                json.dumps(w.get("habitat")),
                json.dumps(w.get("removal")),
                int(w.get("edible", False)), w.get("edible_note"),
                w.get("interesting"), int(w.get("native_to_nl", True)),
            ))
        await db.commit()
        print(f"Seeded {len(WEEDS)} weed species.")


if __name__ == "__main__":
    async def main():
        await init_pool()
        try:
            await seed()
        finally:
            await close_pool()

    asyncio.run(main())
